### ISSUE TITLE
Print PDF in Viewer module is not working aptly

### ISSUE THREAD

**Issue by mcqueide** [groupdocs-total/GroupDocs.Total-for-Java#3] opened 2021-08-19 20:16 UTC
I made a test with branch master, and another test in demo application, in both tests I could print but the document was unformatted.

**Comment by vladimir-litvinchik** [comment] 2021-08-25 06:37
@mcqueide, the issue is under investigation at the moment. We'll let you know in case of any updates.

**Comment by vladimir-litvinchik** [comment] 2021-09-03 07:45
@mcqueide 

This issue has been fixed in the latest commit. Now, when you click print Viewer will create PDF file and open a print dialog.

**Closed as completed** 2021-09-08 14:17 UTC
